CREATE TABLE skill_keywords (
    id BIGSERIAL PRIMARY KEY,
    term VARCHAR(100) NOT NULL,
    normalized_term VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    aliases TEXT[],
    role_tags TEXT[],
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_skill_keywords_normalized_term UNIQUE (normalized_term)
);

CREATE INDEX idx_skill_keywords_enabled
ON skill_keywords (enabled);

CREATE INDEX idx_skill_keywords_category
ON skill_keywords (category);

CREATE INDEX idx_skill_keywords_role_tags
ON skill_keywords USING GIN (role_tags);

INSERT INTO skill_keywords (
    term,
    normalized_term,
    category,
    aliases,
    role_tags
) VALUES
('Java', 'java', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('Python', 'python', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('JavaScript', 'javascript', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('TypeScript', 'typescript', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('C++', 'c++', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('C', 'c', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('Go', 'go', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('Rust', 'rust', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('SQL', 'sql', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('Bash', 'bash', 'Languages', ARRAY[]::text[], ARRAY[]::text[]),
('React', 'react', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('Next.js', 'next.js', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('Node.js', 'node.js', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('HTML', 'html', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('CSS', 'css', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('Tailwind CSS', 'tailwind css', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('Vite', 'vite', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('Axios', 'axios', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('UI', 'ui', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('UX', 'ux', 'Frontend', ARRAY[]::text[], ARRAY[]::text[]),
('Spring Boot', 'spring boot', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('Spring Security', 'spring security', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('REST API', 'rest api', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('REST APIs', 'rest apis', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('MyBatis', 'mybatis', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('JWT', 'jwt', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('BCrypt', 'bcrypt', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('Authentication', 'authentication', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('Authorization', 'authorization', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('Microservices', 'microservices', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('API integration', 'api integration', 'Backend', ARRAY[]::text[], ARRAY[]::text[]),
('PostgreSQL', 'postgresql', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('Postgres', 'postgres', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('MySQL', 'mysql', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('MongoDB', 'mongodb', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('Redis', 'redis', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('JSONB', 'jsonb', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('pgvector', 'pgvector', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('Relational database', 'relational database', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('Database design', 'database design', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('SQL optimization', 'sql optimization', 'Databases', ARRAY[]::text[], ARRAY[]::text[]),
('OpenAI API', 'openai api', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('LLM', 'llm', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('LLMs', 'llms', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Embedding', 'embedding', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Embeddings', 'embeddings', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('RAG', 'rag', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Retrieval', 'retrieval', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Prompt engineering', 'prompt engineering', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Prompt construction', 'prompt construction', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('AI workflow orchestration', 'ai workflow orchestration', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Response validation', 'response validation', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Evaluation', 'evaluation', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Evals', 'evals', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Machine learning', 'machine learning', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Model integration', 'model integration', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Guardrails', 'guardrails', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Latency', 'latency', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Cost optimization', 'cost optimization', 'AI / ML', ARRAY[]::text[], ARRAY[]::text[]),
('Docker', 'docker', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Kubernetes', 'kubernetes', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Git', 'git', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('GitHub', 'github', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('CI/CD', 'ci/cd', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Flyway', 'flyway', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Linux', 'linux', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Cloud', 'cloud', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('AWS', 'aws', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Infrastructure as Code', 'infrastructure as code', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Monitoring', 'monitoring', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Logging', 'logging', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Container orchestration', 'container orchestration', 'Infrastructure', ARRAY[]::text[], ARRAY[]::text[]),
('Data structures', 'data structures', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Algorithms', 'algorithms', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Operating systems', 'operating systems', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Computer networks', 'computer networks', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('TCP/IP', 'tcp/ip', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Distributed systems', 'distributed systems', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Concurrency', 'concurrency', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Multithreading', 'multithreading', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Computer architecture', 'computer architecture', 'CS Fundamentals', ARRAY[]::text[], ARRAY[]::text[]),
('Debugging', 'debugging', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('API debugging', 'api debugging', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Production debugging', 'production debugging', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Root cause analysis', 'root cause analysis', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Unit testing', 'unit testing', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Integration testing', 'integration testing', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Reliability', 'reliability', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Scalability', 'scalability', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Performance', 'performance', 'Testing / Quality', ARRAY[]::text[], ARRAY[]::text[]),
('Embedded systems', 'embedded systems', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('Microcontrollers', 'microcontrollers', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('OpenMV', 'openmv', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('CC3200', 'cc3200', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('UART', 'uart', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('SPI', 'spi', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('I2C', 'i2c', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('GPIO', 'gpio', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('PWM', 'pwm', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('PID control', 'pid control', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('PCB', 'pcb', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('FPGA', 'fpga', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('Verilog', 'verilog', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[]),
('SystemVerilog', 'systemverilog', 'Embedded / Hardware', ARRAY[]::text[], ARRAY[]::text[])
ON CONFLICT (normalized_term) DO NOTHING;
